source/api/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter

from api.views import ImageViewSet, CommentViewSet

app_name = 'api'

router = DefaultRouter()
router.register('image', ImageViewSet)
router.register(r'comments', CommentViewSet)

urlpatterns = [
    path('', include(router.urls)),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
]

source/main/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('webapp.urls')),
    path('api/', include('api.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.urls import path, include

from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('image/<int:pk>/', ImageDetailView.as_view(), name='image_view'),
    path('image/add/', ImageCreateView.as_view(), name='image_create'),
    path('image/<int:pk>/update/', ImageUpdateView.as_view(), name='image_update'),
    path('image/<int:pk>/delete/', ImageDeleteView.as_view(), name='image_delete'),
]

source/webapp/models.py
from django.contrib.auth import get_user_model
from django.db import models


class Image(models.Model):
    image = models.ImageField(null=False, blank=False, upload_to='pics', verbose_name='Фотография')
    description = models.TextField(null=False, blank=False, max_length=2000, verbose_name='Подпись')
    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=1,
                               related_name='images', verbose_name='Автор')

    def __str__(self):
        return self.description

    class Meta:
        verbose_name = 'Фотография'
        verbose_name_plural = 'Фотографии'


class FavoriteImage(models.Model):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='favorite_image', verbose_name='Пользователь')
    image = models.ForeignKey('webapp.Image', on_delete=models.CASCADE,
                              related_name='favorites', verbose_name='Фотография')

    def __str__(self):
        return f'{self.user.username} - {self.image.description}'

    class Meta:
        verbose_name = 'Избранное'


class ImageComment(models.Model):
    text = models.TextField(null=False, blank=False, max_length=400, verbose_name='Текст')
    image = models.ForeignKey('webapp.Image', null=False, blank=False,
                              on_delete=models.CASCADE, verbose_name='Фотография', related_name='comments')

    created_at = models.DateTimeField(auto_now_add=True, verbose_name='Время создания')
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE, default=1,
                               related_name='comments', verbose_name='Автор')

    def __str__(self):
        return self.text[:20]

source/webapp/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin, UserPassesTestMixin
from django.core.paginator import Paginator
from django.shortcuts import render
from django.urls import reverse, reverse_lazy
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from webapp.models import Image
from webapp.mixins import CustomMixin


class IndexView(ListView):
    template_name = 'images/index.html'
    context_object_name = 'images'
    model = Image
    ordering = '-created_at'


class ImageDetailView(DetailView):
    template_name = 'images/detail.html'
    pk_url_kwarg = 'pk'
    model = Image

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comments = context['image'].comments.order_by('-created_at')
        self.paginate_comments_to_context(comments, context)
        context['user'] = self.request.user
        return context

    def paginate_comments_to_context(self, comments, context):
        paginator = Paginator(comments, 10, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        context['paginator'] = paginator
        context['page_obj'] = page
        context['comments'] = page.object_list
        context['is_paginated'] = page.has_other_pages()


class ImageCreateView(CustomMixin, CreateView):
    template_name = 'images/create.html'
    model = Image
    fields = ['image', 'description']

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('webapp:index')


class ImageUpdateView(UserPassesTestMixin, UpdateView):
    model = Image
    template_name = 'images/update.html'
    fields = ['image', 'description', 'author']
    context_object_name = 'obj'

    def test_func(self):
        return self.request.user.has_perm('webapp.change_image') or \
            self.get_object().author == self.request.user

    def get_success_url(self):
        return reverse('webapp:product_view', kwargs={'pk': self.object.pk})


class ImageDeleteView(PermissionRequiredMixin, DeleteView):
    template_name = 'images/delete.html'
    model = Image
    context_object_name = 'image'
    success_url = reverse_lazy('webapp:index')
    permission_required = 'webapp.delete_image'

    def has_permission(self):
        article = self.get_object()
        return super().has_permission() or article.author == self.request.user

source/webapp/templates/images/create.html
{% extends "base.html" %}

{% block title %}Добавить фото{% endblock %}

{% block content %}
   <h1>Добавить фото: </h1>
    {% url 'webapp:image_create' as action_url %}
        {% include 'partial/form.html' with button_text='Добавить' action_url=action_url form_method='post' enctype='multipart/form-data'%}
{% endblock %}

source/webapp/templates/images/delete.html
{% extends "partial/../base.html" %}

{% block title %}Delete{% endblock %}

{% block menu %}
    <li class="nav-item my-2"><a class="nav-link" href="{% url 'webapp:image_view' image.pk %}">Назад</a></li>
{% endblock %}


{% block content %}
    <h1 class="title mt-5">Вы уверены, что хотите удалить данную картинку: "{{ image }}"?</h1>
    <form method="POST" action="{% url "webapp:image_delete" image.pk %}" class="text-center">
        {% csrf_token %}
        <p><input class="btn btn-primary" type="submit" value="Да"></p>
        <p><a class="btn btn-primary" href="{% url "webapp:image_view" image.pk %}" role="button">Нет</a></p>
    </form>
{% endblock %}

source/webapp/templates/images/detail.html
{% extends 'partial/../base.html' %}
{% block content %}
    <div class="card-deck mt-4">
        <div class="card">
            <img class="card-img-top" src="{{ image.image.url }}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{ image.author }}</h5>
                <p class="card-text">{{ image.description }}</p>
                <small class="text-muted">{{ image.created_at }}</small>
            </div>
            <div class="card-footer">
                 {% if perms.webapp.change_image or image.author == request.user %}
                    <a href="{% url 'webapp:image_update' image.pk %}" class="card-link">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil-square" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456l-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/>
                            <path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                        </svg>
                    </a>
                {% endif %}
                {% if perms.webapp.delete_image or image.author == request.user %}
                    <a href="{% url 'webapp:image_delete' image.pk %}" class="card-link">
                        <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-file-earmark-minus" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                            <path d="M9 1H4a2 2 0 0 0-2 2v10a2 2 0 0 0 2 2h5v-1H4a1 1 0 0 1-1-1V3a1 1 0 0 1 1-1h5v2.5A1.5 1.5 0 0 0 10.5 6H13v2h1V6L9 1z"/>
                            <path fill-rule="evenodd" d="M11 11.5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 0 1h-4a.5.5 0 0 1-.5-.5z"/>
                        </svg>
                    </a>
                {% endif %}
            </div>
        </div>
    </div>
    <h2>Комментарии:</h2>
    {% for comment in comments %}
        <div class="comment">
            <p><b>{{ comment.author }}</b> </p>
            <p>commented at {{ comment.created_at|date:'d.m.Y H:i:s' }}</p>
            <div class="pre">{{ comment.text }}</div>
            <hr/>
            <button type="button" class="btn btn-primary" id="{{ comment.id }}" onclick="deleteTasksLoadIndex(this.id)">Delete</button>
        </div>
    {% empty %}
        <p>Нет комментариев</p>
    {% endfor %}
    <button type="button" class="btn btn-primary my-2" data-toggle="modal" data-target="#exampleModal">Добавить комментарий</button>

<!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Создание комментария</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="form-group">
                            <label for="text">Текст</label>
                            <textarea class="form-control" id="text" rows="3"></textarea>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                    <button id="create" type="button" class="btn btn-success" onclick="createTasksLoadIndex($('#text').val(), `{{ user }}`, `{{ image.id }}`)" >Сохранить</button>
                </div>
{% endblock %}

source/webapp/templates/images/index.html
{% extends 'partial/../base.html' %}

{% block title %}Галерея{% endblock %}

{% block content %}
    <div class="title mt-5 pb-4" style="text-align: center"><h1>Добро пожаловать в галерею!</h1></div>
     {% include 'partial/image_list.html' %}
{% endblock %}

source/webapp/templates/images/update.html
{% extends 'base.html' %}

{% block title %}Update{% endblock %}

{% block content %}
    <h1>Редактировать</h1>
    {% url "webapp:mage_update" pk=image.pk as action_url %}
    {% include 'partial/form.html' with action_url=action_url form_method='post' button_text='Редактировать' %}
{% endblock %}